'use client';

import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { TrendingUp } from 'lucide-react';

export const LiveRevenueCounter = () => {
  const [revenue, setRevenue] = useState(5847293);
  const [dailyIncrease, setDailyIncrease] = useState(0);

  useEffect(() => {
    // Simulate real-time updates every 3 seconds
    const interval = setInterval(() => {
      const increment = Math.floor(Math.random() * 1000) + 500;
      setRevenue(prev => prev + increment);
      setDailyIncrease(prev => prev + increment);
    }, 3000);

    // Reset daily counter every 24 hours
    const dailyReset = setInterval(() => {
      setDailyIncrease(0);
    }, 86400000); // 24 hours

    return () => {
      clearInterval(interval);
      clearInterval(dailyReset);
    };
  }, []);

  const formatNumber = (num: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(num);
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="bg-zinc-900/50 backdrop-blur-sm rounded-2xl p-8 border border-zinc-800 holographic"
    >
      <div className="flex items-center gap-4 mb-4">
        <div className="p-3 bg-[#D4AF37]/10 rounded-lg">
          <TrendingUp className="h-8 w-8 text-[#D4AF37]" />
        </div>
        <div>
          <h3 className="text-2xl font-bold">Live Student Revenue</h3>
          <p className="text-sm text-gray-400">Generated by our community this year</p>
        </div>
      </div>

      <div className="space-y-4">
        <div>
          <p className="text-sm text-gray-400 mb-1">Total Revenue Generated</p>
          <p className="text-4xl font-bold revenue-counter">
            {formatNumber(revenue)}
          </p>
        </div>

        <div className="grid grid-cols-2 gap-4">
          <div>
            <p className="text-sm text-gray-400">Today's Increase</p>
            <p className="text-xl font-bold text-green-500">
              +{formatNumber(dailyIncrease)}
            </p>
          </div>
          <div>
            <p className="text-sm text-gray-400">Active Students</p>
            <p className="text-xl font-bold">10,847</p>
          </div>
        </div>

        <div className="pt-4 border-t border-zinc-800">
          <div className="flex items-center gap-2">
            <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></div>
            <p className="text-sm text-gray-400">Live updates every few seconds</p>
          </div>
        </div>
      </div>
    </motion.div>
  );
};
