"use client";

import { usePathname } from "next/navigation";
import { useI18n } from "@/components/i18n-provider";
import type { Lang } from "@/lib/i18n";

type DepthRoute = "visibilityos" | "warriors-team" | "drop";
type DepthCopy = { eyebrow: string; title: string; intro: string; cards: { title: string; text: string }[]; };

const COPY: Record<Lang, Record<DepthRoute, DepthCopy>> = {
  en: {
    visibilityos: { eyebrow: "After the audit", title: "Diagnosis should end in a decision, not another report", intro: "Prove the leak, fix the highest-impact layer first, then check the same journey again.", cards: [{ title: "Prioritize", text: "Separate issues that affect trust, conversion or visibility from cosmetic changes." }, { title: "Implement", text: "Turn the evidence into a short execution list for your team or the relevant Growth System." }, { title: "Re-check", text: "Review the same pages after changes so the next decision is based on evidence." }] },
    "warriors-team": { eyebrow: "What compounds", title: "Skills become more valuable when the room around them gets stronger", intro: "Warriors combines practical learning with implementation, direct review and relationships that can compound over time.", cards: [{ title: "Skill", text: "Build practical capability in AI systems, client acquisition, content and business operations." }, { title: "Execution", text: "Turn learning into real assets, conversations, workflows, content and measurable changes." }, { title: "Network", text: "Use the private community and weekly sessions to unblock work, exchange experience and build stronger relationships." }] },
    drop: { eyebrow: "Before launch", title: "The product has to survive three tests before it deserves scale", intro: "Performance stays in validation until the routine works for real users and the operating model works in the real world.", cards: [{ title: "Repeatability", text: "The product should be simple enough to use repeatedly." }, { title: "Operations", text: "Production, packaging and delivery have to support the promise." }, { title: "Economics", text: "Price and unit economics have to make sense before paid growth." }] },
  },
  ua: {
    visibilityos: { eyebrow: "Після аудиту", title: "Діагностика має завершуватися рішенням, а не ще одним звітом", intro: "Доведіть втрату, спочатку виправте шар із найбільшим впливом, а потім перевірте той самий шлях ще раз.", cards: [{ title: "Пріоритет", text: "Відокремте проблеми довіри, конверсії та видимості від косметичних змін." }, { title: "Впровадження", text: "Перетворіть докази на короткий список дій для команди." }, { title: "Повторна перевірка", text: "Після змін перевірте ті самі сторінки, щоб наступне рішення спиралося на факти." }] },
    "warriors-team": { eyebrow: "Що накопичується", title: "Навички стають ціннішими, коли сильнішає оточення", intro: "Warriors поєднує практичне навчання, реалізацію, прямі розбори та відносини, цінність яких зростає з часом.", cards: [{ title: "Навички", text: "Розвивайте практичні можливості у ШІ-системах, залученні клієнтів, контенті та управлінні бізнесом." }, { title: "Реалізація", text: "Перетворюйте навчання на реальні матеріали, діалоги, автоматизації, контент і вимірювані зміни." }, { title: "Оточення", text: "Використовуйте закриту спільноту й щотижневі сесії, щоб розблоковувати роботу, обмінюватися досвідом і будувати сильніші зв'язки." }] },
    drop: { eyebrow: "До запуску", title: "Продукт має пройти три перевірки, перш ніж його варто масштабувати", intro: "Performance залишається у валідації, доки сам режим не працює для реальних людей, а операційна модель — у реальному світі.", cards: [{ title: "Повторюваність", text: "Продукт має бути достатньо простим для регулярного використання." }, { title: "Операції", text: "Виробництво, пакування та доставка мають підтримувати обіцянку." }, { title: "Економіка", text: "Ціна та юніт-економіка мають сходитися до платного масштабування." }] },
  },
  ru: {
    visibilityos: { eyebrow: "После аудита", title: "Диагностика должна заканчиваться решением, а не ещё одним отчётом", intro: "Докажите потерю, сначала исправьте слой с самым большим влиянием, затем проверьте тот же путь ещё раз.", cards: [{ title: "Приоритет", text: "Отделите проблемы доверия, конверсии и видимости от косметических изменений." }, { title: "Внедрение", text: "Превратите доказательства в короткий список действий для команды." }, { title: "Повторная проверка", text: "После изменений проверьте те же страницы, чтобы следующее решение опиралось на факты." }] },
    "warriors-team": { eyebrow: "Что накапливается", title: "Навыки становятся ценнее, когда сильнее окружение", intro: "Warriors объединяет практическое обучение, реализацию, прямые разборы и отношения, ценность которых может расти со временем.", cards: [{ title: "Навыки", text: "Развивайте практические возможности в ИИ-системах, привлечении клиентов, контенте и управлении бизнесом." }, { title: "Реализация", text: "Превращайте обучение в реальные материалы, диалоги, автоматизации, контент и измеримые изменения." }, { title: "Окружение", text: "Используйте закрытое сообщество и еженедельные сессии, чтобы разблокировать работу, обмениваться опытом и строить более сильные связи." }] },
    drop: { eyebrow: "До запуска", title: "Продукт должен пройти три проверки, прежде чем его стоит масштабировать", intro: "Performance остаётся в валидации, пока сам режим не работает для реальных людей, а операционная модель — в реальном мире.", cards: [{ title: "Повторяемость", text: "Продукт должен быть достаточно простым для регулярного использования." }, { title: "Операции", text: "Производство, упаковка и доставка должны поддерживать обещанный опыт." }, { title: "Экономика", text: "Цена и юнит-экономика должны сходиться до платного масштабирования." }] },
  },
};

const STYLE: Record<DepthRoute, { eyebrow: string; glow: string; border: string; number: string }> = {
  visibilityos: { eyebrow: "text-sky-200/70", glow: "bg-[radial-gradient(ellipse_at_top,rgba(56,189,248,.065),transparent_62%)]", border: "hover:border-sky-300/18", number: "text-sky-200/45" },
  "warriors-team": { eyebrow: "text-violet-200/70", glow: "bg-[radial-gradient(ellipse_at_top,rgba(167,139,250,.065),transparent_62%)]", border: "hover:border-violet-300/18", number: "text-violet-200/45" },
  drop: { eyebrow: "text-emerald-200/70", glow: "bg-[radial-gradient(ellipse_at_top,rgba(52,211,153,.06),transparent_62%)]", border: "hover:border-emerald-300/18", number: "text-emerald-200/45" },
};

function routeFromPath(pathname: string): DepthRoute | null { if (pathname === "/visibilityos" || pathname.endsWith("/visibilityos")) return "visibilityos"; if (pathname === "/warriors-team" || pathname.endsWith("/warriors-team")) return "warriors-team"; if (pathname === "/drop" || pathname.endsWith("/drop")) return "drop"; return null; }

export function PageDepthSection() {
  const { lang } = useI18n(); const pathname = usePathname() || "/"; const route = routeFromPath(pathname); if (!route) return null; const x = COPY[lang][route]; const style = STYLE[route];
  return <section className="relative overflow-hidden border-t border-white/[.06] bg-[#020202] py-20 md:py-24"><div className={`pointer-events-none absolute inset-0 ${style.glow}`} /><div className="container relative z-10 mx-auto max-w-6xl px-4"><div className="mx-auto max-w-4xl text-center"><span className={`text-[10px] font-semibold uppercase tracking-[.24em] ${style.eyebrow}`}>{x.eyebrow}</span><h2 className="section-title mx-auto mt-4 max-w-4xl text-[clamp(2.3rem,4vw,3.8rem)] text-zinc-100">{x.title}</h2><p className="section-lead mx-auto mt-5 max-w-2xl text-sm leading-7 text-zinc-500 sm:text-base sm:leading-8">{x.intro}</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{x.cards.map((card, index) => <div key={card.title} className={`rounded-[24px] border border-white/[.08] bg-white/[.018] p-6 transition-colors ${style.border}`}><span className={`text-[10px] font-semibold tracking-[.16em] ${style.number}`}>0{index + 1}</span><h3 className="mt-4 text-lg font-semibold text-zinc-100">{card.title}</h3><p className="mt-3 text-sm leading-7 text-zinc-500">{card.text}</p></div>)}</div></div></section>;
}
