"use client";

import { useMemo, useState } from "react";
import { motion, useReducedMotion } from "framer-motion";
import { AlertTriangle, ArrowRight, BarChart3, CheckCircle2, ChevronRight, CircleDot, Gauge, Globe2, Loader2, MapPin, MonitorCheck, RefreshCw, Route, ScanSearch, Search, ShieldCheck, Target, TrendingUp, Users, XCircle } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { Header } from "@/components/ui/header";
import { FooterSection } from "@/components/FooterSection";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { DirectionPageHero } from "@/components/ui/direction-page-hero";
import { InteractiveSurface } from "@/components/ui/premium-interaction";
import { submitLead } from "@/lib/site";
import { useI18n } from "@/components/i18n-provider";
import type { Lang } from "@/lib/i18n";
import type { GrowthAction, GrowthLane, ScanFinding, ScanPageSummary, ScanStatus, VisibilitySiteScanResult } from "@/lib/visibilityos-scan";

type ReviewMode = "plan" | "monitoring";
type ProductCopy = {
  badge: string; heroLead: string; heroSupport: string; heroPrimary: string; heroSecondary: string; liveLabel: string; scanTitle: string; scanLead: string;
  urlLabel: string; serviceLabel: string; servicePlaceholder: string; locationLabel: string; locationPlaceholder: string; competitorsLabel: string; competitorsHint: string; competitorPlaceholder: string;
  scanButton: string; scanning: string; scanNote: string; errorTitle: string; scoreLabel: string; scannedPages: string; discoveredPages: string; sitemap: string; robots: string;
  pillarsTitle: string; pillarNames: { search: string; local: string; conversion: string; trust: string }; notAssessed: string;
  queueEyebrow: string; queueTitle: string; queueLead: string; laneNames: Record<GrowthLane, string>; impact: string; confidence: string; effort: string;
  pageMapTitle: string; pageMapLead: string; pageKind: Record<ScanPageSummary["kind"], string>; serviceMatch: string; locationMatch: string;
  competitorTitle: string; competitorLead: string; coreFindings: string; evidence: string; recommendation: string; limitationsTitle: string; scanAnother: string;
  productEyebrow: string; productTitle: string; productLead: string; productSteps: { title: string; text: string; badge: string }[];
  planEyebrow: string; planTitle: string; planLead: string; monitoringTitle: string; monitoringLead: string; planMode: string; monitoringMode: string;
  name: string; email: string; phone: string; context: string; contextPlaceholder: string; submitPlan: string; submitMonitoring: string; sending: string; requestSuccessTitle: string; requestSuccessLead: string; requestError: string; requestNote: string; requestPlanShort: string; joinBetaShort: string;
  faqEyebrow: string; faqTitle: string; faqLead: string; faq: { q: string; a: string }[];
};

const COPY: Record<Lang, ProductCopy> = {
  en: {
    badge: "VisibilityOS · Search, local & conversion intelligence",
    heroLead: "See what search engines, AI crawlers and customers can actually understand from your site — then get a prioritized growth queue.",
    heroSupport: "VisibilityOS samples the real public site, checks crawlability, on-page search signals, local/service coverage, trust and conversion paths, and can compare the same evidence against competitors. No invented rankings.",
    heroPrimary: "Run a Visibility Map", heroSecondary: "See the operating system", liveLabel: "Live product · v2",
    scanTitle: "Audit the site in its real market context", scanLead: "A URL alone is not enough. Add the service you want to win and the location you serve so VisibilityOS can test whether the site actually communicates both.",
    urlLabel: "Website URL", serviceLabel: "Target service / offer", servicePlaceholder: "e.g. roof repair, dental implants, AI automation", locationLabel: "City / service area", locationPlaceholder: "e.g. Manchester, Kharkiv, London",
    competitorsLabel: "Competitor URLs (optional, up to 2)", competitorsHint: "Use competitors you genuinely compete with. VisibilityOS compares the same observable public signals, not private traffic or rankings.", competitorPlaceholder: "competitor.com",
    scanButton: "Build Visibility Map", scanning: "Mapping public site…", scanNote: "Public pages only. The scan samples up to five same-site pages plus robots/sitemap signals. It never logs in, submits forms or claims rankings it cannot observe.", errorTitle: "The Visibility Map could not complete",
    scoreLabel: "observable site readiness", scannedPages: "Pages sampled", discoveredPages: "Pages discovered", sitemap: "Sitemap", robots: "Robots",
    pillarsTitle: "Four layers of the visibility system", pillarNames: { search: "Search & crawl", local: "Local relevance", conversion: "Conversion path", trust: "Trust & entity" }, notAssessed: "Add service/location",
    queueEyebrow: "Growth Queue", queueTitle: "Fix the highest-impact layer first", queueLead: "A short Now / Next / Later queue tied to real evidence, not a report nobody implements.", laneNames: { now: "Now", next: "Next", later: "Later" }, impact: "Impact", confidence: "Confidence", effort: "Effort",
    pageMapTitle: "Page coverage map", pageMapLead: "What VisibilityOS sampled, how each page appears to function, and whether the target service and location are actually visible.", pageKind: { home: "Home", service: "Service", location: "Location", contact: "Contact", about: "About", faq: "FAQ", other: "Other" }, serviceMatch: "Service", locationMatch: "Location",
    competitorTitle: "Competitive context", competitorLead: "Same checks, same scoring model. Use the evidence gap as a clue, not a promise about who ranks first.", coreFindings: "Homepage evidence", evidence: "Evidence", recommendation: "Next move", limitationsTitle: "What VisibilityOS does not pretend to know", scanAnother: "Scan another site",
    productEyebrow: "From tool to operating system", productTitle: "Audit once. Improve. Re-check. Monitor.", productLead: "VisibilityOS is the front door to an ongoing visibility operating system: evidence, implementation queue, re-checks and recurring monitoring from connected data.",
    productSteps: [
      { badge: "01 · Free", title: "Visibility Map", text: "Public-site crawl, market context, evidence, competitors and a prioritized queue." },
      { badge: "02 · Human", title: "30-day Growth Plan", text: "Commercial review of positioning, UX, copy and implementation priorities where automation cannot verify judgment." },
      { badge: "03 · Beta", title: "Weekly Monitoring", text: "Saved project history, evidence deltas and alerts when important site signals change." },
      { badge: "04 · Delivery", title: "Implementation", text: "Ship SEO, conversion, content and automation work, then re-scan the same journey." },
    ],
    planEyebrow: "Next step", planTitle: "Turn the evidence into a 30-day growth plan", planLead: "Send the Visibility Map with your business context. The automated evidence stays attached; judgment-heavy parts are reviewed before recommendations are treated as verified.", monitoringTitle: "Want recurring monitoring instead?", monitoringLead: "Join the monitoring beta for saved projects, weekly re-scans and change alerts.", planMode: "30-day plan", monitoringMode: "Monitoring beta",
    name: "Name", email: "Email", phone: "Phone / messenger", context: "What outcome matters most?", contextPlaceholder: "More qualified local leads, stronger service visibility, clearer offer, better conversion…", submitPlan: "Request 30-day plan", submitMonitoring: "Join monitoring beta", sending: "Sending…", requestSuccessTitle: "Request received", requestSuccessLead: "Your scan context is attached. You do not need to repeat the URL, service, location or findings.", requestError: "Could not send the request. Check the required fields and try again.", requestNote: "No payment is taken here. Rankings, traffic and revenue are never invented from public technical signals.", requestPlanShort: "Request plan", joinBetaShort: "Join beta",
    faqEyebrow: "Methodology", faqTitle: "What the product actually measures", faqLead: "Clear boundaries make the evidence more useful and the claims safer.", faq: [
      { q: "Does VisibilityOS show my real Google ranking?", a: "Not in the public scan. Real ranking and query performance require connected search data or a dedicated search-results source. The free scan only reports signals it can directly observe." },
      { q: "What does the local relevance score mean?", a: "It checks whether the sampled site communicates the target service and location, whether focused pages exist in the sample, and whether business entity structured data is visible. It is not a Map Pack ranking score." },
      { q: "Does it check AI-search visibility?", a: "It checks crawlable entity, content and structured-data signals that help machines understand the site. It does not claim an assistant currently recommends the business unless that is tested separately." },
      { q: "Why only sample a few pages?", a: "The free product is designed to produce a fast baseline without hammering a site. Deeper history and recurring monitoring belong in the account-based product." },
      { q: "What happens after the scan?", a: "Fix the highest-confidence Growth Queue items, re-scan after implementation, and request a human plan for copy, UX, positioning and commercial decisions." },
    ],
  },
  ua: {
    badge: "VisibilityOS · Search, local та conversion intelligence",
    heroLead: "Побачте, що пошуковики, AI-crawler-и та клієнти реально можуть зрозуміти з вашого сайту, а потім отримайте пріоритезовану Growth Queue.",
    heroSupport: "VisibilityOS аналізує публічний сайт, crawlability, on-page search сигнали, покриття послуг і географії, trust та conversion paths і може порівняти ті самі докази з конкурентами. Без вигаданих позицій.",
    heroPrimary: "Побудувати Visibility Map", heroSecondary: "Як працює система", liveLabel: "Живий продукт · v2",
    scanTitle: "Перевірте сайт у реальному ринковому контексті", scanLead: "Одного URL недостатньо. Додайте послугу, яку хочете просувати, і географію роботи, щоб VisibilityOS перевірив, чи сайт справді пояснює обидва фактори.",
    urlLabel: "URL сайту", serviceLabel: "Цільова послуга / офер", servicePlaceholder: "напр. ремонт даху, імплантація, AI automation", locationLabel: "Місто / зона роботи", locationPlaceholder: "напр. Харків, Київ, London",
    competitorsLabel: "URL конкурентів (опційно, до 2)", competitorsHint: "Додавайте реальних комерційних конкурентів. VisibilityOS порівнює ті самі публічні сигнали, а не приватний трафік чи позиції.", competitorPlaceholder: "competitor.com",
    scanButton: "Побудувати Visibility Map", scanning: "Будуємо карту сайту…", scanNote: "Лише публічні сторінки. Скан бере вибірку до п’яти сторінок плюс robots/sitemap. Він не входить в акаунти, не надсилає форми й не вигадує рейтинги.", errorTitle: "Visibility Map не вдалося завершити",
    scoreLabel: "готовність за спостережуваними сигналами", scannedPages: "Сторінок у вибірці", discoveredPages: "Сторінок знайдено", sitemap: "Sitemap", robots: "Robots",
    pillarsTitle: "Чотири шари visibility-системи", pillarNames: { search: "Search & crawl", local: "Local relevance", conversion: "Conversion path", trust: "Trust & entity" }, notAssessed: "Додайте service/location",
    queueEyebrow: "Growth Queue", queueTitle: "Спочатку виправляємо шар із найбільшим впливом", queueLead: "Коротка Now / Next / Later черга, прив’язана до evidence з реального сайту.", laneNames: { now: "Зараз", next: "Далі", later: "Потім" }, impact: "Вплив", confidence: "Впевненість", effort: "Зусилля",
    pageMapTitle: "Карта покриття сторінок", pageMapLead: "Що саме просканував VisibilityOS, яку функцію має сторінка та чи видно на ній цільову послугу й географію.", pageKind: { home: "Головна", service: "Послуга", location: "Локація", contact: "Контакт", about: "Про нас", faq: "FAQ", other: "Інше" }, serviceMatch: "Послуга", locationMatch: "Локація",
    competitorTitle: "Контекст конкурентів", competitorLead: "Ті самі перевірки й та сама модель score. Evidence gap — підказка, а не обіцянка позиції.", coreFindings: "Evidence головної сторінки", evidence: "Доказ", recommendation: "Наступна дія", limitationsTitle: "Чого VisibilityOS не вдає, що знає", scanAnother: "Просканувати інший сайт",
    productEyebrow: "Від tool до operating system", productTitle: "Аудит. Впровадження. Повторна перевірка. Моніторинг.", productLead: "VisibilityOS стає входом у постійну visibility operating system: evidence, implementation queue, re-check та recurring monitoring з підключених даних.",
    productSteps: [
      { badge: "01 · Free", title: "Visibility Map", text: "Public-site crawl, market context, evidence, competitors та пріоритезована черга." },
      { badge: "02 · Human", title: "30-денний Growth Plan", text: "Перевірка positioning, UX, copy та пріоритетів там, де automation не може підтвердити судження." },
      { badge: "03 · Beta", title: "Щотижневий Monitoring", text: "Saved projects, історія evidence та alerts при важливих змінах." },
      { badge: "04 · Delivery", title: "Implementation", text: "Впроваджені SEO, conversion, content та automation зміни й re-scan того самого journey." },
    ],
    planEyebrow: "Наступний крок", planTitle: "Перетворіть evidence на 30-денний growth plan", planLead: "Надішліть Visibility Map із бізнес-контекстом. Автоматичні докази збережуться, а judgment-heavy частини будуть перевірені людиною.", monitoringTitle: "Потрібен recurring monitoring?", monitoringLead: "Приєднайтесь до monitoring beta для saved projects, щотижневих re-scan та change alerts.", planMode: "30-денний план", monitoringMode: "Monitoring beta",
    name: "Ім’я", email: "Email", phone: "Телефон / месенджер", context: "Який результат зараз найважливіший?", contextPlaceholder: "Більше якісних локальних лідів, сильніша видимість послуги, чіткіший офер…", submitPlan: "Запросити 30-денний план", submitMonitoring: "Приєднатись до monitoring beta", sending: "Надсилаємо…", requestSuccessTitle: "Запит отримано", requestSuccessLead: "Контекст скану прикріплено. URL, послугу, локацію та findings повторювати не потрібно.", requestError: "Не вдалося надіслати запит. Перевірте обов’язкові поля й спробуйте ще раз.", requestNote: "Тут немає оплати. Позиції, трафік і виручка ніколи не вигадуються з публічних сигналів.", requestPlanShort: "Запросити план", joinBetaShort: "У beta",
    faqEyebrow: "Методологія", faqTitle: "Що продукт реально вимірює", faqLead: "Чіткі межі роблять evidence кориснішим, а маркетингові обіцянки безпечнішими.", faq: [
      { q: "VisibilityOS показує мою реальну позицію в Google?", a: "Не в публічному скані. Реальні позиції та query performance потребують search-даних або окремого SERP source. Free scan показує лише те, що може спостерігати напряму." },
      { q: "Що означає Local relevance score?", a: "Він перевіряє, чи сайт пояснює цільову послугу й географію, чи є сфокусовані сторінки у вибірці та чи видно business entity structured data. Це не Map Pack ranking score." },
      { q: "Продукт перевіряє AI-search visibility?", a: "Він перевіряє crawlable entity, content та structured-data сигнали. Він не заявляє, що assistant уже рекомендує бізнес, якщо це не перевірено окремо." },
      { q: "Чому сканується лише кілька сторінок?", a: "Free product має швидко дати корисний baseline без агресивного crawling. Глибший monitoring належить до account-based продукту." },
      { q: "Що робити після скану?", a: "Виконайте Growth Queue з найвищою confidence, перескануйте сайт після змін і запитайте human plan для copy, UX та positioning." },
    ],
  },
  ru: {
    badge: "VisibilityOS · Search, local и conversion intelligence",
    heroLead: "Посмотрите, что поисковики, AI-crawler-ы и клиенты реально могут понять из вашего сайта, а затем получите приоритизированную Growth Queue.",
    heroSupport: "VisibilityOS анализирует публичный сайт, crawlability, on-page search сигналы, покрытие услуг и географии, trust и conversion paths и может сравнить те же доказательства с конкурентами. Без выдуманных позиций.",
    heroPrimary: "Построить Visibility Map", heroSecondary: "Как работает система", liveLabel: "Живой продукт · v2",
    scanTitle: "Проверьте сайт в реальном рыночном контексте", scanLead: "Одного URL недостаточно. Добавьте услугу, которую хотите продвигать, и географию работы, чтобы VisibilityOS проверил, действительно ли сайт объясняет оба фактора.",
    urlLabel: "URL сайта", serviceLabel: "Целевая услуга / офер", servicePlaceholder: "например, ремонт крыши, имплантация, AI automation", locationLabel: "Город / зона работы", locationPlaceholder: "например, Харьков, Киев, London",
    competitorsLabel: "URL конкурентов (опционально, до 2)", competitorsHint: "Добавляйте реальных коммерческих конкурентов. VisibilityOS сравнивает одинаковые публичные сигналы, а не приватный трафик или позиции.", competitorPlaceholder: "competitor.com",
    scanButton: "Построить Visibility Map", scanning: "Строим карту сайта…", scanNote: "Только публичные страницы. Скан берёт выборку до пяти страниц плюс robots/sitemap. Он не входит в аккаунты, не отправляет формы и не выдумывает рейтинги.", errorTitle: "Visibility Map не удалось завершить",
    scoreLabel: "готовность по наблюдаемым сигналам", scannedPages: "Страниц в выборке", discoveredPages: "Страниц найдено", sitemap: "Sitemap", robots: "Robots",
    pillarsTitle: "Четыре слоя visibility-системы", pillarNames: { search: "Search & crawl", local: "Local relevance", conversion: "Conversion path", trust: "Trust & entity" }, notAssessed: "Добавьте service/location",
    queueEyebrow: "Growth Queue", queueTitle: "Сначала исправляем слой с самым большим влиянием", queueLead: "Короткая Now / Next / Later очередь, привязанная к evidence из реального сайта.", laneNames: { now: "Сейчас", next: "Дальше", later: "Потом" }, impact: "Влияние", confidence: "Уверенность", effort: "Сложность",
    pageMapTitle: "Карта покрытия страниц", pageMapLead: "Что именно просканировал VisibilityOS, какую функцию выполняет страница и видны ли на ней целевая услуга и география.", pageKind: { home: "Главная", service: "Услуга", location: "Локация", contact: "Контакт", about: "О нас", faq: "FAQ", other: "Другое" }, serviceMatch: "Услуга", locationMatch: "Локация",
    competitorTitle: "Контекст конкурентов", competitorLead: "Те же проверки и та же модель score. Evidence gap — подсказка, а не обещание позиции.", coreFindings: "Evidence главной страницы", evidence: "Доказательство", recommendation: "Следующий шаг", limitationsTitle: "Чего VisibilityOS не делает вид, что знает", scanAnother: "Просканировать другой сайт",
    productEyebrow: "От tool к operating system", productTitle: "Аудит. Внедрение. Повторная проверка. Мониторинг.", productLead: "VisibilityOS становится входом в постоянную visibility operating system: evidence, implementation queue, re-check и recurring monitoring из подключённых данных.",
    productSteps: [
      { badge: "01 · Free", title: "Visibility Map", text: "Public-site crawl, market context, evidence, competitors и приоритизированная очередь." },
      { badge: "02 · Human", title: "30-дневный Growth Plan", text: "Проверка positioning, UX, copy и приоритетов там, где automation не может подтвердить суждение." },
      { badge: "03 · Beta", title: "Еженедельный Monitoring", text: "Saved projects, история evidence и alerts при важных изменениях." },
      { badge: "04 · Delivery", title: "Implementation", text: "Внедрённые SEO, conversion, content и automation изменения и re-scan того же journey." },
    ],
    planEyebrow: "Следующий шаг", planTitle: "Превратите evidence в 30-дневный growth plan", planLead: "Отправьте Visibility Map с бизнес-контекстом. Автоматические доказательства сохранятся, а judgment-heavy части будут проверены человеком.", monitoringTitle: "Нужен recurring monitoring?", monitoringLead: "Присоединитесь к monitoring beta для saved projects, еженедельных re-scan и change alerts.", planMode: "30-дневный план", monitoringMode: "Monitoring beta",
    name: "Имя", email: "Email", phone: "Телефон / мессенджер", context: "Какой результат сейчас важнее всего?", contextPlaceholder: "Больше качественных локальных лидов, сильнее видимость услуги, понятнее офер…", submitPlan: "Запросить 30-дневный план", submitMonitoring: "Присоединиться к monitoring beta", sending: "Отправляем…", requestSuccessTitle: "Запрос получен", requestSuccessLead: "Контекст скана прикреплён. URL, услугу, локацию и findings повторять не нужно.", requestError: "Не удалось отправить запрос. Проверьте обязательные поля и попробуйте ещё раз.", requestNote: "Здесь нет оплаты. Позиции, трафик и выручка никогда не выдумываются из публичных сигналов.", requestPlanShort: "Запросить план", joinBetaShort: "В beta",
    faqEyebrow: "Методология", faqTitle: "Что продукт реально измеряет", faqLead: "Чёткие границы делают evidence полезнее, а маркетинговые обещания безопаснее.", faq: [
      { q: "VisibilityOS показывает мою реальную позицию в Google?", a: "Не в публичном скане. Реальные позиции и query performance требуют search-данных или отдельного SERP source. Free scan показывает только то, что может наблюдать напрямую." },
      { q: "Что означает Local relevance score?", a: "Он проверяет, ясно ли сайт объясняет целевую услугу и географию, есть ли сфокусированные страницы в выборке и видны ли business entity structured data. Это не Map Pack ranking score." },
      { q: "Продукт проверяет AI-search visibility?", a: "Он проверяет crawlable entity, content и structured-data сигналы. Он не заявляет, что assistant уже рекомендует бизнес, если это не проверено отдельно." },
      { q: "Почему сканируется только несколько страниц?", a: "Free product должен быстро дать полезный baseline без агрессивного crawling. Более глубокий monitoring относится к account-based продукту." },
      { q: "Что делать после скана?", a: "Выполните Growth Queue с самой высокой confidence, пересканируйте сайт после изменений и запросите human plan для copy, UX и positioning." },
    ],
  },
};

const STATUS_ORDER: Record<ScanStatus, number> = { fail: 0, warn: 1, pass: 2 };
const PRIORITY_ORDER = { high: 0, medium: 1, low: 2 } as const;
const PRODUCT_ICONS: LucideIcon[] = [ScanSearch, Target, MonitorCheck, TrendingUp];
function statusUi(status: ScanStatus) { if (status === "pass") return { icon: CheckCircle2, border: "border-emerald-300/15", bg: "bg-emerald-300/[.035]", text: "text-emerald-300" }; if (status === "warn") return { icon: AlertTriangle, border: "border-amber-300/15", bg: "bg-amber-300/[.035]", text: "text-amber-300" }; return { icon: XCircle, border: "border-red-300/15", bg: "bg-red-300/[.035]", text: "text-red-300" }; }
function queueUi(lane: GrowthLane) { if (lane === "now") return { border: "border-red-300/15", bg: "bg-red-300/[.025]", text: "text-red-200" }; if (lane === "next") return { border: "border-amber-300/15", bg: "bg-amber-300/[.025]", text: "text-amber-200" }; return { border: "border-sky-300/15", bg: "bg-sky-300/[.025]", text: "text-sky-200" }; }
function safeDate(value: string) { try { return new Date(value).toLocaleString(); } catch { return value; } }

function PillarCard({ label, value, icon: Icon, empty }: { label: string; value: number | null; icon: LucideIcon; empty: string }) {
  const score = value ?? 0;
  return <div className="rounded-[22px] border border-white/[.075] bg-white/[.018] p-5"><div className="flex items-center justify-between gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl border border-sky-300/15 bg-sky-300/[.035] text-sky-200"><Icon className="h-4 w-4" /></span>{value === null ? <span className="text-[10px] text-zinc-650">{empty}</span> : <span className="font-display text-3xl tracking-[-.04em] text-zinc-100">{value}</span>}</div><p className="mt-4 text-sm font-medium text-zinc-300">{label}</p><div className="mt-3 h-1 overflow-hidden rounded-full bg-white/[.05]"><div className="h-full rounded-full bg-gradient-to-r from-sky-400 via-sky-200 to-amber-200" style={{ width: `${value === null ? 0 : Math.max(4, score)}%` }} /></div></div>;
}
function GrowthActionCard({ item, copy }: { item: GrowthAction; copy: ProductCopy }) {
  const ui = queueUi(item.lane);
  return <div className={`rounded-[24px] border ${ui.border} ${ui.bg} p-5 sm:p-6`}><div className="flex flex-wrap items-center justify-between gap-3"><span className={`rounded-full border ${ui.border} px-2.5 py-1 text-[9px] font-semibold uppercase tracking-[.16em] ${ui.text}`}>{copy.laneNames[item.lane]}</span><div className="flex flex-wrap gap-2 text-[9px] uppercase tracking-[.12em] text-zinc-650"><span>{copy.impact}: {item.impact}</span><span>·</span><span>{copy.confidence}: {item.confidence}</span><span>·</span><span>{copy.effort}: {item.effort}</span></div></div><h3 className="mt-4 text-lg font-semibold text-zinc-100">{item.title}</h3><p className="mt-2 text-sm leading-7 text-zinc-450">{item.reason}</p><div className="mt-4 grid gap-3 md:grid-cols-2"><div className="rounded-2xl border border-white/[.06] bg-black/25 p-4"><p className="text-[9px] font-semibold uppercase tracking-[.15em] text-zinc-650">{copy.evidence}</p><p className="mt-2 break-words text-xs leading-6 text-zinc-400">{item.evidence}</p></div><div className="rounded-2xl border border-white/[.06] bg-black/25 p-4"><p className="text-[9px] font-semibold uppercase tracking-[.15em] text-zinc-650">{copy.recommendation}</p><p className="mt-2 text-xs leading-6 text-zinc-400">{item.action}</p></div></div></div>;
}
function FindingCard({ finding }: { finding: ScanFinding }) {
  const ui = statusUi(finding.status); const Icon = ui.icon;
  return <div className={`rounded-[22px] border ${ui.border} ${ui.bg} p-5`}><div className="flex gap-3"><span className={`mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-xl border ${ui.border} bg-black/25 ${ui.text}`}><Icon className="h-4 w-4" /></span><div className="min-w-0"><h3 className="text-sm font-semibold text-zinc-100">{finding.title}</h3><p className="mt-1 text-xs leading-6 text-zinc-450">{finding.detail}</p><p className="mt-3 break-words text-[11px] leading-5 text-zinc-650">{finding.evidence}</p></div></div></div>;
}

export function VisibilityOsMarketPage() {
  const { lang } = useI18n(); const copy = COPY[lang]; const reduced = useReducedMotion();
  const [url, setUrl] = useState(""); const [service, setService] = useState(""); const [location, setLocation] = useState(""); const [competitors, setCompetitors] = useState(["", ""]); const [showCompetitors, setShowCompetitors] = useState(false);
  const [scanning, setScanning] = useState(false); const [scanError, setScanError] = useState(""); const [result, setResult] = useState<VisibilitySiteScanResult | null>(null);
  const [review, setReview] = useState<Record<string, string>>({}); const [reviewMode, setReviewMode] = useState<ReviewMode>("plan"); const [reviewSubmitting, setReviewSubmitting] = useState(false); const [reviewDone, setReviewDone] = useState(false); const [reviewError, setReviewError] = useState(false);
  const sortedFindings = useMemo(() => result ? [...result.findings].sort((a, b) => STATUS_ORDER[a.status] - STATUS_ORDER[b.status] || PRIORITY_ORDER[a.priority] - PRIORITY_ORDER[b.priority]).slice(0, 8) : [], [result]);
  const runScan = async () => {
    if (!url.trim()) return; setScanning(true); setScanError(""); setResult(null); setReviewDone(false); setReviewError(false);
    try { const response = await fetch("/api/visibilityos/scan", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ url: url.trim(), service: service.trim(), location: location.trim(), competitors: competitors.map((value) => value.trim()).filter(Boolean), lang }) }); const data = await response.json() as { ok?: boolean; result?: VisibilitySiteScanResult; error?: string }; if (!response.ok || !data.ok || !data.result) throw new Error(data.error || "Scan failed"); setResult(data.result); requestAnimationFrame(() => document.getElementById("results")?.scrollIntoView({ behavior: reduced ? "auto" : "smooth", block: "start" })); } catch (error) { setScanError(error instanceof Error ? error.message : "Scan failed"); } finally { setScanning(false); }
  };
  const focusRequest = (mode: ReviewMode) => { setReviewMode(mode); requestAnimationFrame(() => document.getElementById("request-plan")?.scrollIntoView({ behavior: reduced ? "auto" : "smooth", block: "start" })); };
  const submitRequest = async () => {
    if (!result || !review.name?.trim() || !review.email?.trim()) { setReviewError(true); return; } setReviewSubmitting(true); setReviewError(false);
    const ok = await submitLead({ intent: reviewMode === "monitoring" ? "visibilityos_monitoring_beta" : "visibilityos_30_day_growth_plan", language: lang, buttonLabel: reviewMode === "monitoring" ? "VisibilityOS - Monitoring beta" : "VisibilityOS - 30 day growth plan", website: result.resolvedUrl, targetService: result.context.service, targetLocation: result.context.location, observableScore: result.score, searchPillar: result.pillars.search, localPillar: result.pillars.local, conversionPillar: result.pillars.conversion, trustPillar: result.pillars.trust, pagesScanned: result.site.pagesScanned, pagesDiscovered: result.site.pagesDiscovered, growthQueue: result.growthQueue.slice(0, 7).map((item) => `${item.lane.toUpperCase()} · ${item.title} · ${item.evidence}`), competitors: result.competitors.map((item) => `${item.resolvedUrl} · ${item.score}`), scanTimestamp: result.scannedAt, ...review });
    setReviewSubmitting(false); if (ok) setReviewDone(true); else setReviewError(true);
  };
  const resetScan = () => { setResult(null); setScanError(""); setUrl(""); setService(""); setLocation(""); setCompetitors(["", ""]); window.scrollTo({ top: document.getElementById("scan")?.offsetTop || 0, behavior: reduced ? "auto" : "smooth" }); };
  const structuredData = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "VisibilityOS", applicationCategory: "BusinessApplication", operatingSystem: "Web", offers: { "@type": "Offer", price: "0", priceCurrency: "USD", category: "Visibility Map" }, description: copy.heroSupport, url: lang === "en" ? "https://vladkuzmenko.com/visibilityos" : `https://vladkuzmenko.com/${lang}/visibilityos`, featureList: ["Public website crawl", "SEO and crawl evidence", "Local service and location coverage", "Conversion path checks", "Competitor evidence comparison", "Prioritized Growth Queue"] };
  const faqStructuredData = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: copy.faq.map((item) => ({ "@type": "Question", name: item.q, acceptedAnswer: { "@type": "Answer", text: item.a } })) };

  return <div className="min-h-screen overflow-x-hidden bg-[#020202] text-white"><Header /><main>
    <DirectionPageHero accent="blue" eyebrow={copy.badge} titleA="Visibility" titleB="OS." lead={copy.heroLead} support={copy.heroSupport}><a href="#scan"><Button className="premium-button h-auto min-h-12 px-8 py-3.5">{copy.heroPrimary}<ArrowRight className="ml-2 h-4 w-4" /></Button></a><a href="#product"><Button className="h-auto min-h-12 border border-sky-200/18 bg-sky-200/[.05] px-8 py-3.5 text-white hover:bg-sky-200/[.09]">{copy.heroSecondary}<Route className="ml-2 h-4 w-4" /></Button></a></DirectionPageHero>
    <section id="scan" className="relative scroll-mt-24 overflow-hidden py-20 md:py-28"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_at_50%_0%,rgba(56,189,248,.11),transparent_62%)]" aria-hidden="true" /><div className="container relative z-10 mx-auto max-w-5xl px-4"><div className="mx-auto max-w-3xl text-center"><span className="inline-flex items-center gap-2 rounded-full border border-emerald-300/15 bg-emerald-300/[.035] px-3 py-1.5 text-[10px] font-semibold uppercase tracking-[.18em] text-emerald-200"><CircleDot className="h-3.5 w-3.5" />{copy.liveLabel}</span><h1 className="section-title mt-5 text-[clamp(2.5rem,5vw,4.6rem)] text-zinc-100">{copy.scanTitle}</h1><p className="section-lead mx-auto mt-5 max-w-2xl text-sm leading-7 text-zinc-400 sm:text-base sm:leading-8">{copy.scanLead}</p></div>
      <InteractiveSurface accent="blue" lift={false} className="relative mx-auto mt-10 overflow-hidden rounded-[32px] border border-sky-200/[.14] bg-[linear-gradient(145deg,rgba(125,211,252,.06),rgba(255,255,255,.018),rgba(0,0,0,.48))] p-5 sm:p-8">{!reduced && scanning ? <motion.div aria-hidden="true" className="absolute inset-x-5 top-0 h-px bg-gradient-to-r from-transparent via-sky-300 to-transparent shadow-[0_0_30px_rgba(125,211,252,.7)]" animate={{ y: [20, 310, 20] }} transition={{ duration: 2.8, repeat: Infinity, ease: "easeInOut" }} /> : null}<div className="grid gap-5">
        <div><label htmlFor="visibility-url" className="text-sm font-medium text-zinc-300">{copy.urlLabel}</label><div className="relative mt-2"><Globe2 className="pointer-events-none absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-zinc-600" /><Input id="visibility-url" value={url} onChange={(event) => setUrl(event.target.value)} placeholder="example.com" className="h-13 border-white/10 bg-black/35 pl-11 text-base text-white placeholder:text-zinc-700" /></div></div>
        <div className="grid gap-4 md:grid-cols-2"><div><label htmlFor="visibility-service" className="text-sm font-medium text-zinc-300">{copy.serviceLabel}</label><div className="relative mt-2"><Target className="pointer-events-none absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-zinc-600" /><Input id="visibility-service" value={service} onChange={(event) => setService(event.target.value)} placeholder={copy.servicePlaceholder} className="h-12 border-white/10 bg-black/35 pl-11 text-white placeholder:text-zinc-700" /></div></div><div><label htmlFor="visibility-location" className="text-sm font-medium text-zinc-300">{copy.locationLabel}</label><div className="relative mt-2"><MapPin className="pointer-events-none absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-zinc-600" /><Input id="visibility-location" value={location} onChange={(event) => setLocation(event.target.value)} placeholder={copy.locationPlaceholder} className="h-12 border-white/10 bg-black/35 pl-11 text-white placeholder:text-zinc-700" /></div></div></div>
        <button type="button" onClick={() => setShowCompetitors((value) => !value)} className="flex w-fit items-center gap-2 text-left text-xs font-medium text-sky-200/75 transition-colors hover:text-sky-100"><Users className="h-4 w-4" />{copy.competitorsLabel}<ChevronRight className={`h-3.5 w-3.5 transition-transform ${showCompetitors ? "rotate-90" : ""}`} /></button>
        {showCompetitors ? <div className="rounded-[22px] border border-white/[.07] bg-black/25 p-4 sm:p-5"><p className="text-xs leading-6 text-zinc-600">{copy.competitorsHint}</p><div className="mt-3 grid gap-3 md:grid-cols-2">{competitors.map((value, index) => <Input key={index} value={value} onChange={(event) => setCompetitors((old) => old.map((item, itemIndex) => itemIndex === index ? event.target.value : item))} placeholder={copy.competitorPlaceholder} className="border-white/10 bg-black/35 text-white placeholder:text-zinc-700" />)}</div></div> : null}
        <Button onClick={() => void runScan()} disabled={scanning || !url.trim()} className="premium-button h-13 w-full px-6 disabled:opacity-50">{scanning ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" />{copy.scanning}</> : <><ScanSearch className="mr-2 h-4 w-4" />{copy.scanButton}</>}</Button><div className="flex gap-2 text-xs leading-6 text-zinc-600"><ShieldCheck className="mt-1 h-3.5 w-3.5 shrink-0 text-sky-300/55" /><p>{copy.scanNote}</p></div>{scanError ? <div className="rounded-2xl border border-red-300/15 bg-red-300/[.035] p-4"><div className="flex gap-3"><XCircle className="mt-0.5 h-4 w-4 shrink-0 text-red-300" /><div><p className="text-sm font-semibold text-red-200">{copy.errorTitle}</p><p className="mt-1 text-sm leading-6 text-zinc-400">{scanError}</p></div></div></div> : null}
      </div></InteractiveSurface></div></section>
    {result ? <section id="results" className="scroll-mt-24 pb-24"><div className="container mx-auto max-w-6xl px-4">
      <div className="grid gap-5 lg:grid-cols-[.72fr_1.28fr]"><div className="rounded-[30px] border border-sky-200/[.13] bg-[radial-gradient(circle_at_50%_0%,rgba(56,189,248,.10),transparent_48%),rgba(255,255,255,.018)] p-6 sm:p-8"><p className="text-[10px] font-semibold uppercase tracking-[.22em] text-sky-200/70">Visibility Map</p><div className="mt-6 flex items-end gap-4"><span className="font-display text-7xl font-medium tracking-[-.06em] text-white sm:text-8xl">{result.score}</span><div className="pb-3"><span className="text-2xl text-zinc-600">/100</span><p className="mt-1 text-xs text-zinc-500">{copy.scoreLabel}</p></div></div><p className="mt-6 break-all text-xs leading-6 text-zinc-600">{result.resolvedUrl}</p><p className="mt-1 text-[11px] text-zinc-700">{safeDate(result.scannedAt)}</p></div>
        <div className="rounded-[30px] border border-white/[.08] bg-white/[.018] p-6 sm:p-8"><p className="text-sm font-semibold text-zinc-200">{copy.pillarsTitle}</p><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><PillarCard label={copy.pillarNames.search} value={result.pillars.search} icon={Search} empty={copy.notAssessed} /><PillarCard label={copy.pillarNames.local} value={result.pillars.local} icon={MapPin} empty={copy.notAssessed} /><PillarCard label={copy.pillarNames.conversion} value={result.pillars.conversion} icon={Route} empty={copy.notAssessed} /><PillarCard label={copy.pillarNames.trust} value={result.pillars.trust} icon={ShieldCheck} empty={copy.notAssessed} /></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><div className="rounded-2xl border border-white/[.055] bg-black/20 p-4"><p className="text-2xl font-semibold text-zinc-200">{result.site.pagesScanned}</p><p className="mt-1 text-[10px] text-zinc-650">{copy.scannedPages}</p></div><div className="rounded-2xl border border-white/[.055] bg-black/20 p-4"><p className="text-2xl font-semibold text-zinc-200">{result.site.pagesDiscovered}</p><p className="mt-1 text-[10px] text-zinc-650">{copy.discoveredPages}</p></div><div className="rounded-2xl border border-white/[.055] bg-black/20 p-4"><p className={`text-sm font-semibold ${result.site.sitemapFound ? "text-emerald-300" : "text-amber-300"}`}>{result.site.sitemapFound ? "Found" : "Review"}</p><p className="mt-1 text-[10px] text-zinc-650">{copy.sitemap}</p></div><div className="rounded-2xl border border-white/[.055] bg-black/20 p-4"><p className={`text-sm font-semibold ${result.site.robotsFound ? "text-emerald-300" : "text-amber-300"}`}>{result.site.robotsFound ? "Found" : "Review"}</p><p className="mt-1 text-[10px] text-zinc-650">{copy.robots}</p></div></div></div></div>
      <div className="mx-auto mt-16 max-w-3xl text-center"><p className="text-[10px] font-semibold uppercase tracking-[.22em] text-amber-300/70">{copy.queueEyebrow}</p><h2 className="section-title mt-4 text-[clamp(2.45rem,4.6vw,4.2rem)] text-zinc-100">{copy.queueTitle}</h2><p className="mt-4 text-sm leading-7 text-zinc-400 sm:text-base">{copy.queueLead}</p></div><div className="mt-9 grid gap-4">{result.growthQueue.map((item) => <GrowthActionCard key={item.id} item={item} copy={copy} />)}</div>
      <div className="mt-16 grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><div className="rounded-[30px] border border-white/[.08] bg-white/[.018] p-6 sm:p-8"><h2 className="text-xl font-semibold text-zinc-100">{copy.pageMapTitle}</h2><p className="mt-2 max-w-2xl text-sm leading-7 text-zinc-500">{copy.pageMapLead}</p><div className="mt-6 space-y-3">{result.pages.map((page) => <div key={page.url} className="rounded-[20px] border border-white/[.06] bg-black/25 p-4"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full border border-sky-300/12 bg-sky-300/[.025] px-2 py-1 text-[9px] font-semibold uppercase tracking-[.13em] text-sky-200/75">{copy.pageKind[page.kind]}</span><span className="text-[10px] text-zinc-700">HTTP {page.statusCode}</span></div><p className="mt-2 truncate text-sm font-medium text-zinc-300">{page.title || page.path}</p><p className="mt-1 truncate text-[11px] text-zinc-650">{page.path}</p></div><div className="flex shrink-0 gap-2">{result.context.service ? <span className={`rounded-lg border px-2 py-1 text-[9px] ${page.serviceMatch ? "border-emerald-300/15 bg-emerald-300/[.035] text-emerald-300" : "border-white/[.06] text-zinc-700"}`}>{copy.serviceMatch}</span> : null}{result.context.location ? <span className={`rounded-lg border px-2 py-1 text-[9px] ${page.locationMatch ? "border-emerald-300/15 bg-emerald-300/[.035] text-emerald-300" : "border-white/[.06] text-zinc-700"}`}>{copy.locationMatch}</span> : null}</div></div></div>)}</div></div>
        <div className="space-y-5"><div className="rounded-[30px] border border-white/[.08] bg-white/[.018] p-6"><h2 className="text-xl font-semibold text-zinc-100">{copy.coreFindings}</h2><div className="mt-5 grid gap-3">{sortedFindings.map((finding) => <FindingCard key={finding.id} finding={finding} />)}</div></div><div className="rounded-[30px] border border-amber-300/[.10] bg-amber-300/[.025] p-6"><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-amber-200" /><h3 className="text-lg font-semibold text-zinc-100">{copy.limitationsTitle}</h3></div><ul className="mt-5 space-y-4">{result.limitations.map((item) => <li key={item} className="flex gap-3 text-xs leading-6 text-zinc-500"><ChevronRight className="mt-1.5 h-3.5 w-3.5 shrink-0 text-amber-300/55" />{item}</li>)}</ul></div></div></div>
      {result.competitors.length ? <div className="mt-16 rounded-[32px] border border-violet-300/[.11] bg-[radial-gradient(circle_at_50%_0%,rgba(167,139,250,.08),transparent_48%),rgba(255,255,255,.018)] p-6 sm:p-8"><h2 className="text-2xl font-semibold text-zinc-100">{copy.competitorTitle}</h2><p className="mt-2 max-w-2xl text-sm leading-7 text-zinc-500">{copy.competitorLead}</p><div className="mt-6 grid gap-4 md:grid-cols-2">{result.competitors.map((competitor) => <div key={competitor.resolvedUrl} className="rounded-[22px] border border-white/[.07] bg-black/25 p-5"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><p className="truncate text-sm font-semibold text-zinc-200">{competitor.title || competitor.resolvedUrl}</p><p className="mt-1 truncate text-[11px] text-zinc-650">{competitor.resolvedUrl}</p></div><span className="font-display text-4xl text-violet-200">{competitor.score}</span></div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><span className="rounded-xl border border-emerald-300/10 p-2 text-xs text-emerald-300">{competitor.summary.pass} ✓</span><span className="rounded-xl border border-amber-300/10 p-2 text-xs text-amber-300">{competitor.summary.warn} !</span><span className="rounded-xl border border-red-300/10 p-2 text-xs text-red-300">{competitor.summary.fail} ×</span></div></div>)}</div></div> : null}
      <div className="mt-8 flex justify-center"><Button onClick={resetScan} variant="outline" className="border-white/10 bg-white/[.025] text-zinc-300 hover:bg-white/[.05] hover:text-white"><RefreshCw className="mr-2 h-4 w-4" />{copy.scanAnother}</Button></div>
      <div id="request-plan" className="mt-16 scroll-mt-24 overflow-hidden rounded-[34px] border border-amber-300/[.12] bg-[radial-gradient(circle_at_50%_0%,rgba(212,175,55,.08),transparent_45%),rgba(255,255,255,.018)] p-6 sm:p-9"><div className="mx-auto max-w-3xl text-center"><p className="text-[10px] font-semibold uppercase tracking-[.22em] text-amber-300/70">{copy.planEyebrow}</p><h2 className="section-title mt-4 text-3xl text-zinc-100 sm:text-5xl">{reviewMode === "monitoring" ? copy.monitoringTitle : copy.planTitle}</h2><p className="mx-auto mt-4 max-w-2xl text-sm leading-7 text-zinc-400">{reviewMode === "monitoring" ? copy.monitoringLead : copy.planLead}</p></div><div className="mx-auto mt-7 flex max-w-xl rounded-xl border border-white/[.08] bg-black/30 p-1"><button type="button" onClick={() => setReviewMode("plan")} className={`flex-1 rounded-lg px-3 py-2 text-xs font-medium ${reviewMode === "plan" ? "bg-white/[.08] text-white" : "text-zinc-600"}`}>{copy.planMode}</button><button type="button" onClick={() => setReviewMode("monitoring")} className={`flex-1 rounded-lg px-3 py-2 text-xs font-medium ${reviewMode === "monitoring" ? "bg-white/[.08] text-white" : "text-zinc-600"}`}>{copy.monitoringMode}</button></div>
        {reviewDone ? <div className="mx-auto mt-8 max-w-2xl rounded-[24px] border border-emerald-300/15 bg-emerald-300/[.035] p-7 text-center"><CheckCircle2 className="mx-auto h-8 w-8 text-emerald-300" /><h3 className="mt-4 text-xl font-semibold text-zinc-100">{copy.requestSuccessTitle}</h3><p className="mt-2 text-sm leading-7 text-zinc-400">{copy.requestSuccessLead}</p></div> : <div className="mx-auto mt-8 grid max-w-3xl gap-4"><div className="grid gap-4 sm:grid-cols-2"><div><label className="text-sm text-zinc-300">{copy.name} *</label><Input value={review.name || ""} onChange={(event) => setReview((old) => ({ ...old, name: event.target.value }))} className="mt-1.5 border-white/10 bg-black/30 text-white" /></div><div><label className="text-sm text-zinc-300">{copy.email} *</label><Input type="email" value={review.email || ""} onChange={(event) => setReview((old) => ({ ...old, email: event.target.value }))} className="mt-1.5 border-white/10 bg-black/30 text-white" /></div></div><div><label className="text-sm text-zinc-300">{copy.phone}</label><Input value={review.phone || ""} onChange={(event) => setReview((old) => ({ ...old, phone: event.target.value }))} className="mt-1.5 border-white/10 bg-black/30 text-white" /></div><div><label className="text-sm text-zinc-300">{copy.context}</label><textarea value={review.context || ""} onChange={(event) => setReview((old) => ({ ...old, context: event.target.value }))} placeholder={copy.contextPlaceholder} rows={4} className="mt-1.5 w-full resize-none rounded-md border border-white/10 bg-black/30 px-3 py-2 text-sm leading-6 text-white outline-none placeholder:text-zinc-700 focus:border-amber-300/30" /></div>{reviewError ? <p className="text-sm text-red-300">{copy.requestError}</p> : null}<Button onClick={() => void submitRequest()} disabled={reviewSubmitting || !review.name?.trim() || !review.email?.trim()} className="premium-button h-12 w-full disabled:opacity-50">{reviewSubmitting ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" />{copy.sending}</> : reviewMode === "monitoring" ? <><MonitorCheck className="mr-2 h-4 w-4" />{copy.submitMonitoring}</> : <><BarChart3 className="mr-2 h-4 w-4" />{copy.submitPlan}</>}</Button><p className="text-center text-[11px] leading-5 text-zinc-650">{copy.requestNote}</p></div>}
      </div>
    </div></section> : null}
    <section id="product" className="relative scroll-mt-24 overflow-hidden py-24 md:py-28"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_at_50%_0%,rgba(125,211,252,.065),transparent_62%)]" aria-hidden="true" /><div className="container relative z-10 mx-auto max-w-6xl px-4"><div className="mx-auto max-w-3xl text-center"><span className="text-[10px] font-semibold uppercase tracking-[.24em] text-sky-200/70">{copy.productEyebrow}</span><h2 className="section-title mt-4 text-[clamp(2.55rem,4.7vw,4.4rem)] text-zinc-100">{copy.productTitle}</h2><p className="mx-auto mt-5 max-w-2xl text-sm leading-7 text-zinc-400 sm:text-base">{copy.productLead}</p></div><div className="relative mt-12 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{copy.productSteps.map((step, index) => { const Icon = PRODUCT_ICONS[index] ?? Gauge; return <motion.div key={step.title} initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .06 }} className="rounded-[24px] border border-white/[.08] bg-black/40 p-6"><span className="flex h-10 w-10 items-center justify-center rounded-xl border border-sky-300/18 bg-[#03080b] text-sky-200"><Icon className="h-4 w-4" /></span><p className="mt-5 text-[9px] font-semibold uppercase tracking-[.17em] text-zinc-700">{step.badge}</p><h3 className="mt-2 text-lg font-semibold text-zinc-100">{step.title}</h3><p className="mt-3 text-sm leading-7 text-zinc-500">{step.text}</p>{index === 1 ? <button type="button" onClick={() => focusRequest("plan")} className="mt-5 inline-flex items-center gap-1 text-xs font-medium text-amber-200/80 hover:text-amber-100">{copy.requestPlanShort}<ArrowRight className="h-3.5 w-3.5" /></button> : null}{index === 2 ? <button type="button" onClick={() => focusRequest("monitoring")} className="mt-5 inline-flex items-center gap-1 text-xs font-medium text-sky-200/80 hover:text-sky-100">{copy.joinBetaShort}<ArrowRight className="h-3.5 w-3.5" /></button> : null}</motion.div>; })}</div></div></section>
    <section className="border-t border-white/[.06] py-24 md:py-28"><div className="container mx-auto max-w-4xl px-4"><div className="text-center"><span className="text-[10px] font-semibold uppercase tracking-[.24em] text-amber-300/70">{copy.faqEyebrow}</span><h2 className="section-title mt-4 text-[clamp(2.4rem,4.4vw,4rem)] text-zinc-100">{copy.faqTitle}</h2><p className="mx-auto mt-4 max-w-2xl text-sm leading-7 text-zinc-500">{copy.faqLead}</p></div><div className="mt-10 space-y-3">{copy.faq.map((item) => <details key={item.q} className="group rounded-[22px] border border-white/[.075] bg-white/[.018] p-5 open:border-sky-300/15"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-sm font-semibold text-zinc-200"><span>{item.q}</span><ChevronRight className="h-4 w-4 shrink-0 text-zinc-600 transition-transform group-open:rotate-90" /></summary><p className="mt-4 pr-6 text-sm leading-7 text-zinc-500">{item.a}</p></details>)}</div></div></section>
  </main><FooterSection /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqStructuredData) }} /></div>;
}
